---
name: Module-Runtime
version: 0.006
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: runtime module handling
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Math::Complex: 0
  Math::Trig: 0
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  Module::Runtime:
    file: lib/Module/Runtime.pm
    version: 0.006
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
